// Minhas Finanças — O que mudou em cada versão: [título, texto]. A tela de novidades mostra só o que é novo para quem
// está atualizando, e o publicar.ps1 copia a lista da versão atual para o versao.json (a prévia que o app mostra
// antes de atualizar). Formato fixo: uma versão por linha, em JSON (aspas duplas), a mais nova primeiro.
const NOVIDADES = {
  "1.50": [["Conta compartilhada do zero", "Agora dá para criar uma conta compartilhada limpa, sem os lançamentos de ninguém. Os dados pessoais de cada um ficam guardados na própria conta."], ["Conta compartilhada mais simples", "As formas de começar ficam numa tela só, com o código do convite sempre à vista e menos toques para convidar ou entrar."], ["Sair encerra para todos", "Quando alguém sai, a conta compartilhada é encerrada: a outra pessoa volta sozinha para a conta individual e a planilha é apagada. Cada um pode ficar com uma cópia dos lançamentos."]],
  "1.49": [["Apagar por dia, mês ou ano", "Em Gastos, Ganhos e Investimentos há um botão para apagar tudo de um dia, de um mês, de um ano ou tudo de uma vez. O que sai vai para a lixeira e dá para desfazer."], ["Planilha em Excel, já formatada", "A exportação do ano agora é um arquivo do Excel com três abas (resumo, gastos e ganhos), cabeçalho colorido, linhas alternadas e totais em destaque."], ["Relatório em PDF mais bonito", "O relatório do mês ganhou faixa de título, cabeçalhos coloridos, linhas alternadas e totais destacados."], ["Aviso antes de importar o extrato", "Ao importar, o app explica qual arquivo espera (OFX ou CSV) e quais colunas o CSV precisa ter."], ["Histórico de sugestões do banco", "No Resumo, o botão Histórico de sugestões lista o que o app leu das notificações, com um botão para lançar o gasto."]],
  "1.48": [["Vale-transporte", "Além de alimentação e refeição, agora há o vale-transporte, com saldo próprio e fora dos totais do mês."], ["Lançar no vale ficou mais rápido", "O formulário de vale pede só o valor, qual vale, a empresa e a descrição. Categoria, banco e conta saíram."], ["Empresa do vale", "Escolha a empresa numa lista (Alelo, Pluxee, Sodexo, Ticket, VR, iFood Benefícios, Ben e outras). A última usada já vem marcada."], ["Histórico do vale", "Toque num vale para ver o saldo e tudo o que entrou e saiu nele, mês a mês."]],
  "1.47": [["Resumo novo", "Gastos do mês e do ano lado a lado no mesmo cartão, uma rosca mostrando para onde foi o dinheiro do mês e um calendário em que os dias com mais gasto ficam mais escuros. Toque num dia para ver o que saiu."], ["Assistente em botão flutuante", "O assistente saiu do menu de baixo: agora é um botão redondo presente em todas as telas."], ["Mais recente ou mais antigo", "Em Gastos e em Ganhos, um botão no título da lista troca a ordem dos lançamentos."], ["Ganhos mais organizados", "Cada ganho mostra as informações em etiquetas, como nos gastos, inclusive quem adicionou na conta compartilhada."]],
  "1.46": [["58 temas novos", "Temas inspirados em filmes, desenhos, super-heróis, contos e animes, cada um com cores, mascote e falas próprios."], ["Temas por categoria", "Os temas especiais ganharam uma área só deles em Configurações › Temas especiais, separados por categoria e com o mascote de cada um à vista."], ["Ícones mais limpos", "O ícone de cada tema foi redesenhado: o personagem grande e centrado, com a marca do app num selo discreto."], ["Ícone no iPhone", "Na versão web, o ícone acompanha o tema escolhido na hora de adicionar o app à Tela de Início."]],
  "1.45": [["Mascotes de verdade", "Cada tema especial agora tem um personagem próprio, não mais o porquinho fantasiado: carro de corrida, caranguejo, lua, sapo mago, alienígena, buldogue, gato da sorte, urso viking, leão espartano e outros."], ["Ícones com mais personalidade", "O ícone de cada tema traz o personagem dele com as barras do app. Para quem não usa tema especial, há cinco desenhos novos: moeda, carteira, em alta, cofre e pizza. Em Configurações › Ícone e bloqueio."], ["Nome escrito por você", "Crie na tela inicial um atalho do app com o nome que quiser. Em Configurações › Ícone e bloqueio."], ["Abertura animada", "Ao abrir, o app mostra uma animação nas cores escolhidas ou no jeito do tema especial."], ["Widget de gastos", "Um widget novo com a lista dos gastos do mês; você escolhe o que entra e a ordem."], ["Widgets mais bonitos", "Visual novo, fundo na cor do app (ou escuro), listas que rolam e o mesmo mascote do app."], ["Atualizações sem confusão", "Procurar atualizações avisa quando você já está na versão mais recente, e os avisos aparecem um de cada vez."]],
  "1.44": [["Seis temas novos", "Grand Prix, Corrida de rua, Drift, Fusca de corrida, Vikings e Espartano, cada um com mascote, falas, animação, ícone e widgets próprios. Em Configurações › Aparência › Tema especial."]],
  "1.43": [["Prévia de várias versões", "Se você pular versões, o aviso de atualização mostra o que vem em cada uma delas."]],
  "1.42": [["Assistente mais limpo", "As sugestões de pergunta aparecem só no começo da conversa; depois de enviar algo, ficam lá em cima no histórico. A conversa recomeça cada vez que você abre o app."], ["Widgets no tema", "Os widgets da tela inicial usam as cores e o mascote do tema especial escolhido."], ["Ícone do tema", "Cada tema especial tem um ícone próprio para o app: as barras de sempre com o símbolo do tema."]],
  "1.41": [["Vale-refeição e alimentação separados", "Novas partes Vales nas abas Gastos e Ganhos, com o saldo de cada vale. Os vales não entram mais nos totais do mês, e há um bloco no Resumo e uma linha no widget. Ao lançar pelo aviso do banco, o app pergunta se foi no vale."], ["Mascotes e falas por tema", "Cada tema especial tem um personagem próprio (robô, unicórnio, piloto, gato DJ, coruja, pintor…) com falas no estilo do tema, e animações diferentes."], ["Mais temas", "Noite estrelada, mais fiel ao quadro, e os temas Bruxo, Espaço, Floresta, Retrô e Dragão."], ["Histórico de versões", "Cada versão agora fica registrada em github.com/GabrielGior/minhas-financas-app/releases, com o que mudou."]],
  "1.40": [["Temas especiais e mais cores", "Em Configurações › Aparência: seis cores novas e os temas Hacker, Boneca, Corrida, Neon, Papel antigo, Praia e Noite estrelada, que mudam o app inteiro, as animações, o mascote e, se você quiser, o ícone."], ["Widgets novos", "Na tela inicial do celular: Resumo (você escolhe as linhas), Contas a vencer e Porquinho, com ou sem o porquinho. Em Configurações › Widgets."], ["Ícone e nome do app", "Em Configurações › Ícone e bloqueio: escolha a cor, o desenho (gráfico ou porquinho) e o nome que aparece na tela inicial."], ["Guia do app", "Em Configurações › Guia do app: todas as funções, onde ficam e como usar, com busca."], ["Erros mais claros e bancos à vista", "Se faltar algo ao salvar, uma mensagem explica e o campo fica destacado. As sugestões de banco aparecem sem precisar tocar no campo."], ["Aviso de versão nova", "Ao abrir, o app procura atualização e mostra o que vem nela, com botão para atualizar na hora. Também há um botão em Configurações."], ["Novidades só do que mudou", "Esta tela passou a mostrar apenas o que é novo na versão que você acabou de receber."]],
  "1.38": [["Planilha do Google ligada ao app", "Em Gastos ou em Configurações › Dados e ajustes: o app cria uma planilha na sua conta Google. O que você lançar no app aparece nela, e o que escrever nela aparece no app."], ["Atualização automática", "O app procura versões novas sozinho ao abrir."], ["Valor mais fácil de digitar", "Digite só os números: a vírgula dos centavos entra sozinha. O valor fica vermelho no gasto e verde no ganho."]],
  "1.37": [["Versão web", "O app também abre no navegador e no iPhone, em gabrielgior.github.io/minhas-financas/app."]],
  "1.35": [["Conta compartilhada", "Casal ou família: duas contas Google vendo e lançando nos mesmos dados, cada um no seu celular e com o seu nome. Cada lançamento mostra quem fez."], ["Gastos separados", "Na aba Gastos, os lançamentos ficam em Assinaturas, Fixos e anuais, Parceladas e Ocasionais, cada grupo com o seu total."], ["Mais de 100 conquistas", "No modo divertido, as conquistas agora têm níveis: do primeiro gasto ao milésimo."], ["Configurações por categoria", "Perfil, Aparência, Lembretes, Conta e as outras opções ficam cada uma no seu botão."]]
};
