// Minhas Finanças — O que mudou em cada versão: [título, texto]. A tela de novidades mostra só o que é novo para quem
// está atualizando, e o publicar.ps1 copia a lista da versão atual para o versao.json (a prévia que o app mostra
// antes de atualizar). Formato fixo: uma versão por linha, em JSON (aspas duplas), a mais nova primeiro.
const NOVIDADES = {
  "1.60": [["Gráfico de linha", "O bloco Ganhos e gastos do ano virou um gráfico de linha: uma linha verde para os ganhos e uma vermelha para os gastos, com um ponto por mês. Os meses futuros aparecem tracejados. Tocar num mês continua mostrando os números dele."]],
  "1.59": [["Conta compartilhada conferida a cada minuto", "Com o app aberto, ele passa a conferir a cada minuto o que as outras pessoas lançaram. Com o app fechado continua a cada 15 minutos, mais ou menos."], ["Cores nos cartões de saldo", "No saldo do mês e no saldo do ano, os ganhos aparecem em verde, os gastos em vermelho e o saldo em branco, em qualquer tema."], ["Gastos por categoria", "O bloco Para onde foi o dinheiro agora se chama Gastos por categoria em (mês), e o bloco do ano ganhou a mesma aparência: rosca com o total no centro e as maiores categorias ao lado. O calendário passou a se chamar Calendário de gastos de (mês)."]],
  "1.58": [["Resumo do mês em destaque", "O bloco do mês no Resumo ganhou o mesmo cartão do saldo do ano: saldo em destaque, com ganhos e gastos embaixo. Tocar nele abre os gastos do mês."], ["Previsão dos próximos meses", "Cada mês virou um cartão com o selo de sobra ou falta, uma barra mostrando quanto dos ganhos os gastos consomem e os valores que entram e saem."], ["Calendário do Resumo", "Todo gasto sem dia informado (inclusive fixos e parcelados) aparece no dia do mês em que foi cadastrado."]],
  "1.57": [["Avisos da conta compartilhada com o app fechado", "O celular passou a conferir a conta a cada 15 minutos (antes era de hora em hora) e o app pede a permissão de notificações a quem já estava na conta. Em Configurações › Conta compartilhada dá para ver quando foi a última conferência, testar a notificação e conferir na hora. É preciso instalar a atualização do app."], ["Calendário do Resumo", "Os dias usam as cores do tema, e um gasto sem dia informado aparece no dia em que foi cadastrado."], ["Gráfico de ganhos e gastos", "Novo visual: totais do ano no topo, barras arredondadas, mês atual em destaque e meses futuros mais claros."], ["Resumo sem repetição", "O Resumo mostra só o botão Pessoal / Compartilhada; a faixa de qual conta está em uso fica nas outras telas."]],
  "1.56": [["Trocar entre conta pessoal e compartilhada", "Quem está numa conta compartilhada ganhou, no Resumo, o botão Pessoal / Compartilhada. A conta pessoal mostra só os seus dados; a compartilhada continua ligada e dá para voltar quando quiser."], ["Qual conta está em uso", "Uma faixa no topo de todas as telas diz se você está na conta pessoal ou na compartilhada. Tocar nela também troca de conta."]],
  "1.55": [["Resumo por mês e ano", "O filtro do Resumo agora escolhe mês e ano: use as setas ou toque no mês. Os cartões do topo, a rosca e o calendário acompanham o mês escolhido, com um visual mais caprichado (barra de quanto dos ganhos foi gasto, comparação com o mês anterior e valores na legenda)."], ["Soma rápida nos valores", "Abaixo de todo campo de valor há os botões +10, +20, +50 e +100. Cada toque soma ao que já está no campo."], ["Conta compartilhada: pessoas e avisos", "Em Configurações › Conta compartilhada aparece a lista de quem está na conta. O app avisa quando outra pessoa entra ou adiciona/edita um gasto, ganho ou investimento: na tela e, com o app fechado, por notificação do celular (precisa instalar a atualização do app)."], ["Carregando", "Uma faixa animada no topo aparece sempre que o app está esperando a internet, e as ações demoradas mostram o que está sendo feito."], ["Assistente mais limpo", "A saudação veio em três balões curtos, as sugestões diminuíram e o botão do olho saiu da tela."], ["Nomes dos temas", "Os temas especiais voltaram a ter nomes neutros, sem paródias."]],
  "1.54": [["Cada tema com a sua animação", "Todo tema especial ganhou uma figura só dele, com um movimento que combina com ela: o navio navega, a bola rola, a roleta gira, os morcegos voam. Ela aparece no topo da tela, na abertura, na comemoração e ao lançar um gasto."], ["Ordenar gastos", "O botão Mais recente / Mais antigo agora inverte a lista sempre, mesmo quando os gastos não têm dia informado."], ["Gastos com o mesmo cartão das outras abas", "O total do mês em Gastos passou a usar o cartão de destaque, igual a Ganhos, Investir e Resumo."]],
  "1.53": [["84 temas novos", "Temas gerais (Cerejeira, Faroeste, Cassino, Futebol, Vampiro…), animes, jogos, desenhos, filmes e séries, cada um com cores, personagem, falas, fundo animado e animações próprios."], ["Novas categorias", "Em Configurações › Temas especiais há agora Temas gerais, Jogos e Séries, além de Filmes, Desenhos, Super-heróis, Contos e Animes."]],
  "1.52": [["Fundo animado em todos os temas", "Cada tema especial ganhou uma cena própria atrás da tela (horizonte, astro e partículas) que fica se movendo o tempo todo."], ["Animações de cada tema", "A abertura ficou mais demorada e muda com o tema, assim como a troca de tela, a comemoração e a animação de um novo gasto, que usam as formas e as cores do tema."]],
  "1.51": [["Puxar para atualizar", "Com a tela no topo, puxe para baixo e solte: o app sincroniza com a conta, atualiza taxas e cotações e redesenha a tela."], ["Mais segurança", "O app ficou mais fechado: os dados não entram no backup do Android, toda a comunicação é só por conexão segura e nenhum site de fora abre dentro do app."]],
  "1.50": [["Conta compartilhada do zero", "Agora dá para criar uma conta compartilhada limpa, sem os lançamentos de ninguém. Os dados pessoais de cada um ficam guardados na própria conta."], ["Conta compartilhada mais simples", "As formas de começar ficam numa tela só, com o código do convite sempre à vista e menos toques para convidar ou entrar."], ["Sair encerra para todos", "Quando alguém sai, a conta compartilhada é encerrada: a outra pessoa volta sozinha para a conta individual e a planilha é apagada. Cada um pode ficar com uma cópia dos lançamentos."]],
  "1.49": [["Apagar por dia, mês ou ano", "Em Gastos, Ganhos e Investimentos há um botão para apagar tudo de um dia, de um mês, de um ano ou tudo de uma vez. O que sai vai para a lixeira e dá para desfazer."], ["Planilha em Excel, já formatada", "A exportação do ano agora é um arquivo do Excel com três abas (resumo, gastos e ganhos), cabeçalho colorido, linhas alternadas e totais em destaque."], ["Relatório em PDF mais bonito", "O relatório do mês ganhou faixa de título, cabeçalhos coloridos, linhas alternadas e totais destacados."], ["Aviso antes de importar o extrato", "Ao importar, o app explica qual arquivo espera (OFX ou CSV) e quais colunas o CSV precisa ter."], ["Histórico de sugestões do banco", "No Resumo, o botão Histórico de sugestões lista o que o app leu das notificações, com um botão para lançar o gasto."]],
  "1.48": [["Vale-transporte", "Além de alimentação e refeição, agora há o vale-transporte, com saldo próprio e fora dos totais do mês."], ["Lançar no vale ficou mais rápido", "O formulário de vale pede só o valor, qual vale, a empresa e a descrição. Categoria, banco e conta saíram."], ["Empresa do vale", "Escolha a empresa numa lista (Alelo, Pluxee, Sodexo, Ticket, VR, iFood Benefícios, Ben e outras). A última usada já vem marcada."], ["Histórico do vale", "Toque num vale para ver o saldo e tudo o que entrou e saiu nele, mês a mês."]],
  "1.47": [["Resumo novo", "Gastos do mês e do ano lado a lado no mesmo cartão, uma rosca mostrando para onde foi o dinheiro do mês e um calendário em que os dias com mais gasto ficam mais escuros. Toque num dia para ver o que saiu."], ["Assistente em botão flutuante", "O assistente saiu do menu de baixo: agora é um botão redondo presente em todas as telas."], ["Mais recente ou mais antigo", "Em Gastos e em Ganhos, um botão no título da lista troca a ordem dos lançamentos."], ["Ganhos mais organizados", "Cada ganho mostra as informações em etiquetas, como nos gastos, inclusive quem adicionou na conta compartilhada."]],
  "1.46": [["58 temas novos", "Temas inspirados em filmes, desenhos, super-heróis, contos e animes, cada um com cores, mascote e falas próprios."], ["Temas por categoria", "Os temas especiais ganharam uma área só deles em Configurações › Temas especiais, separados por categoria e com o mascote de cada um à vista."], ["Ícones mais limpos", "O ícone de cada tema foi redesenhado: o personagem grande e centrado, com a marca do app num selo discreto."], ["Ícone no iPhone", "Na versão web, o ícone acompanha o tema escolhido na hora de adicionar o app à Tela de Início."]],
  "1.45": [["Mascotes de verdade", "Cada tema especial agora tem um personagem próprio, não mais o porquinho fantasiado: carro de corrida, caranguejo, lua, sapo mago, alienígena, buldogue, gato da sorte, urso viking, leão espartano e outros."], ["Ícones com mais personalidade", "O ícone de cada tema traz o personagem dele com as barras do app. Para quem não usa tema especial, há cinco desenhos novos: moeda, carteira, em alta, cofre e pizza. Em Configurações › Ícone e bloqueio."], ["Nome escrito por você", "Crie na tela inicial um atalho do app com o nome que quiser. Em Configurações › Ícone e bloqueio."], ["Abertura animada", "Ao abrir, o app mostra uma animação nas cores escolhidas ou no jeito do tema especial."], ["Widget de gastos", "Um widget novo com a lista dos gastos do mês; você escolhe o que entra e a ordem."], ["Widgets mais bonitos", "Visual novo, fundo na cor do app (ou escuro), listas que rolam e o mesmo mascote do app."], ["Atualizações sem confusão", "Procurar atualizações avisa quando você já está na versão mais recente, e os avisos aparecem um de cada vez."]],
  "1.44": [["Seis temas novos", "Grand Prix, Corrida de rua, Drift, Fusca de corrida, Vikings e Espartano, cada um com mascote, falas, animação, ícone e widgets próprios. Em Configurações › Aparência › Tema especial."]],
  "1.43": [["Prévia de várias versões", "Se você pular versões, o aviso de atualização mostra o que vem em cada uma delas."]],
  "1.42": [["Assistente mais limpo", "As sugestões de pergunta aparecem só no começo da conversa; depois de enviar algo, ficam lá em cima no histórico. A conversa recomeça cada vez que você abre o app."], ["Widgets no tema", "Os widgets da tela inicial usam as cores e o mascote do tema especial escolhido."], ["Ícone do tema", "Cada tema especial tem um ícone próprio para o app: as barras de sempre com o símbolo do tema."]],
  "1.41": [["Vale-refeição e alimentação separados", "Novas partes Vales nas abas Gastos e Ganhos, com o saldo de cada vale. Os vales não entram mais nos totais do mês, e há um bloco no Resumo e uma linha no widget. Ao lançar pelo aviso do banco, o app pergunta se foi no vale."], ["Mascotes e falas por tema", "Cada tema especial tem um personagem próprio (robô, unicórnio, piloto, gato DJ, coruja, pintor…) com falas no estilo do tema, e animações diferentes."], ["Mais temas", "Noite estrelada, mais fiel ao quadro, e os temas Bruxo, Espaço, Floresta, Retrô e Dragão."], ["Histórico de versões", "Cada versão agora fica registrada em github.com/GabrielGior/minhas-financas-app/releases, com o que mudou."]],
  "1.40": [["Temas especiais e mais cores", "Em Configurações › Aparência: seis cores novas e os temas Hacker, Boneca, Corrida, Neon, Papel antigo, Praia e Noite estrelada, que mudam o app inteiro, as animações, o mascote e, se você quiser, o ícone."], ["Widgets novos", "Na tela inicial do celular: Resumo (você escolhe as linhas), Contas a vencer e Porquinho, com ou sem o porquinho. Em Configurações › Widgets."], ["Ícone e nome do app", "Em Configurações › Ícone e bloqueio: escolha a cor, o desenho (gráfico ou porquinho) e o nome que aparece na tela inicial."], ["Guia do app", "Em Configurações › Guia do app: todas as funções, onde ficam e como usar, com busca."], ["Erros mais claros e bancos à vista", "Se faltar algo ao salvar, uma mensagem explica e o campo fica destacado. As sugestões de banco aparecem sem precisar tocar no campo."], ["Aviso de versão nova", "Ao abrir, o app procura atualização e mostra o que vem nela, com botão para atualizar na hora. Também há um botão em Configurações."], ["Novidades só do que mudou", "Esta tela passou a mostrar apenas o que é novo na versão que você acabou de receber."]],
  "1.38": [["Planilha do Google ligada ao app", "Em Gastos ou em Configurações › Dados e ajustes: o app cria uma planilha na sua conta Google. O que você lançar no app aparece nela, e o que escrever nela aparece no app."], ["Atualização automática", "O app procura versões novas sozinho ao abrir."], ["Valor mais fácil de digitar", "Digite só os números: a vírgula dos centavos entra sozinha. O valor fica vermelho no gasto e verde no ganho."]],
  "1.37": [["Versão web", "O app também abre no navegador e no iPhone, em gabrielgior.github.io/minhas-financas/app."]],
  "1.35": [["Conta compartilhada", "Casal ou família: duas contas Google vendo e lançando nos mesmos dados, cada um no seu celular e com o seu nome. Cada lançamento mostra quem fez."], ["Gastos separados", "Na aba Gastos, os lançamentos ficam em Assinaturas, Fixos e anuais, Parceladas e Ocasionais, cada grupo com o seu total."], ["Mais de 100 conquistas", "No modo divertido, as conquistas agora têm níveis: do primeiro gasto ao milésimo."], ["Configurações por categoria", "Perfil, Aparência, Lembretes, Conta e as outras opções ficam cada uma no seu botão."]]
};
